### ISSUE TITLE
Single monolithic jar

### ISSUE THREAD

**Issue by bitsofinfo** [jwilsoncredera/gradle-profiles#2]
So lets say I wanted to be able to create one executable monolithic fat jar from the root that contained all compiled code and dependencies from all sub-projects? How would I modify the build.gradle in the root for this kind of behavior?

**Comment by jdwilson11** [comment]
I don't think you could do it from the root, but you might be able to set up a third sub-project that contains something like this in its build.gradle file to make it a superset of the other subprojects:

```
dependencies {
  compile project(':Profiles-Blog-Sender')
  compile project(':Profiles-Blog-Receiver')
}
```

Note that this example won't work for this particular blog due to a property conflict on "server.port", but this would be the general approach to making a monolith out of subprojects.

Also, make sure this is present, it makes all your external dependencies get packaged inside the JAR:
`apply plugin: 'io.spring.dependency-management'`
Ensure your monolith sub-project's build.gradle doesn't have bootRepackage {enabled=false}, or it will disable that repackaging feature.
